# Example .mock.yaml config
Endpoints:
  - Resource: /city/1
    Method: GET
    Response:
      '[{
        "Id": 1,
        "Name": "Albuquerque",
        "Population": 559,374,
        "State": "New Mexico",
      }]'
    StatusCode: 200

  - Resource: /city
    Method: POST
    Response:
      '[{ 
        "Name": "Albuquerque", 
        "Population": 559, 374, 
        "State": "New Mexico" 
      }]'
    statusCode: 200

  - Resource: /city/1
    Method: PUT
    Response: 
      '[{ 
        "Population": 601, 255 
      }]'
    StatusCode: 204

  - Resource: /city/1
    Method: DELETE
    StatusCode: 204
